<?php
$CONFIG = array (
  'passwordsalt' => 'DEFINED DURING INSTALLATION',
  'secret' => 'DEFINED DURING INSTALLATION',
  'trusted_domains' =>
  array (
    0 => 'localhost',
    1 => 'IP OF DEVICE',
    ),
  'overwritehost' => 'domain.duckdns.org:8443',
  'overwriteprotocol' => 'https',
  'datadirectory' => '/media/myCloudDrive/nextcloud_data',
  'dbtype' => 'mysql',
  'version' => '27.0.2.1',
  'hashingThreads' => 4,
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'filelocking.enabled' => true,
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' => array ('host' => '/run/redis/redis-server.sock', 'port' => 0,),
  'overwrite.cli.url' => 'http://localhost',
  'dbname' => 'nextcloud',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'oc_admin',
  'dbpassword' => 'DEFINED DURING INSTALLATION',
  'installed' => true,
  'instanceid' => 'DEFINED DURING INSTALLATION ',
  'maintenance' => false,
  array (
    'host' => 'localhost',
    'port' => 6379,
  ),
  'enabledPreviewProviders' =>
  array (
    0 => 'OC\\Preview\\PNG',
    1 => 'OC\\Preview\\JPEG',
    2 => 'OC\\Preview\\GIF',
    3 => 'OC\\Preview\\BMP',
    4 => 'OC\\Preview\\XBitmap',
    5 => 'OC\\Preview\\Movie',
    6 => 'OC\\Preview\\PDF',
    7 => 'OC\\Preview\\MP3',
    8 => 'OC\\Preview\\TXT',
    9 => 'OC\\Preview\\MarkDown',
    10 => 'OC\\Preview\\Image',
    11 => 'OC\\Preview\\HEIC',
    12 => 'OC\\Preview\\TIFF',
  ),
  'trashbin_retention_obligation' => 'auto,30',
  'versions_retention_obligation' => 'auto,30',

);
